# Browsersync config
BROWSERSYNC:
  # URL of local development server goes here (ex. http://localsite.dev)
  url: "https://magento.gastro.lan"

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"
  
# Set to true if you want static asset revisioning, helpful for cache busting
REVISIONING: false  

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
    - "!src/assets/{img,js,scss}/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules/foundation-sites/scss"
    - "node_modules/motion-ui/src"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "src/assets/js/app.js"
  # Paths for the package task to include/exclude in .zip archive
  package:
    - "**/*"
    - "!**/node_modules/**"
    - "!**/packaged/**"
    - "!**/src/**"
    - "!**/codesniffer.ruleset.xml"
    - "!**/composer.json"
    - "!**/composer.lock"
    - "!**/config.yml"
    - "!**/config.default.yml"
    - "!**/gulpfile.babel.js"
    - "!**/package.json"
    - "!**/package-lock.json"
    - "!**/webpack.config.js"
  # Paths for PHP CodeSniffer
  phpcs:
    - "**/*.php"
    - "!wpcs"
    - "!wpcs/**"
  # Path to images
  img:
    - "node_modules/lightgallery/src/img/**"
  # Path to fonts & icons
  fonts:
    - "node_modules/components-font-awesome/webfonts/**"
    - "node_modules/lightgallery/src/fonts/**"
  js:
    - "src/assets/js/accordion.js"
    - "src/assets/js/opcheckout.js"
    - "node_modules/jquery/dist/jquery.min.js"
    - "src/assets/js/serviceworker-cache-polyfill.js"
    - "node_modules/lightgallery/dist/js/lightgallery.min.js"
    - "node_modules/lightgallery/lib/jquery.mousewheel.min.js"
    - "node_modules/owl.carousel/dist/owl.carousel.min.js"
    - "node_modules/pwstrength-foundation/dist/pwstrength-foundation.js"

